9uttery/MADII-Server

- scripts/health_check.sh
- scripts/run_new_was.sh
> [Fix] 알림 중복 적용 수정 (#132)

- scripts/run_new_was.sh
- scripts/switch.sh
> [Fix] 배포 시 Helath Check 완료 후 서버 꺼지도록 수정 (#132)

- src/main/java/com/guttery/madii/domain/notification/application/service/UnfinishedAchievementNotificationSendService.java
close #155 
- 미실천 소확행 알림 문구 반영
> [Feature] 미실천 소확행 알림 문구 반영

- src/main/java/com/guttery/madii/domain/albums/application/service/AlbumService.java
- src/main/java/com/guttery/madii/domain/albums/domain/repository/AlbumQueryDslRepository.java
- src/main/java/com/guttery/madii/domain/albums/infrastructure/AlbumRepositoryImpl.java
- src/main/java/com/guttery/madii/domain/albums/presentation/AlbumController.java
#159 
- 전체 앨범 조회 페이징 적용 제거
특별히 봐주었으면 하는 부분이 있다면 작성해 주세요.
> [Fix] 전체 앨범 조회 페이징 적용 제거

- src/main/java/com/guttery/madii/domain/albums/infrastructure/AlbumRepositoryImpl.java
- src/main/java/com/guttery/madii/domain/albums/presentation/AlbumController.java
#159 
- 전체 앨범 조회 페이징 적용 다시 추가
특별히 봐주었으면 하는 부분이 있다면 작성해 주세요.
> [Fix] 전체 앨범 조회 페이징 적용 다시 추가

- src/main/java/com/guttery/madii/domain/user/application/service/LoginService.java
- src/main/java/com/guttery/madii/domain/user/domain/model/User.java
close #163
- 로그인 시 비밀번호 일치 여부 검증하도록 수정
> [Fix] 로그인 시 비밀번호 일치 여부 검증하도록 수정 (#163)

- src/main/java/com/guttery/madii/domain/albums/application/service/AlbumService.java
#166 
- 앨범 생성 시, 배경-아이콘 색 조합 중 분홍-주황 제외 조건 구현
> [Feature ]앨범 생성 시, 배경-아이콘 색 조합 중 분홍-주황 제외 조건 구현

- src/main/java/com/guttery/madii/domain/albums/application/service/AlbumService.java
- src/main/java/com/guttery/madii/domain/albums/domain/repository/AlbumQueryDslRepository.java
- src/main/java/com/guttery/madii/domain/albums/infrastructure/AlbumRepositoryImpl.java
close #167 
- QA-44 (남의 앨범 저장 시 내부 소확행 전부 북마크 활성화)
> [QA] QA-44 (남의 앨범 저장 시 내부 소확행 전부 북마크 활성화)

- src/main/java/com/guttery/madii/domain/user/domain/model/User.java
close #170
- 영속성 전이 설정 추가로 탈퇴 오류 해결
> [Fix] User 도메인에 Album과의 영속성 전이 설정 추가 (#170)

- src/main/java/com/guttery/madii/domain/albums/domain/model/Album.java
close #170
- 영속성 전이 설정 누락된 것 추가
> [Fix] Album 도메인에 SavingAlbum과의 영속성 전이 설정 추가 (#170)

- src/main/java/com/guttery/madii/domain/albums/domain/repository/AlbumQueryDslRepository.java
- src/main/java/com/guttery/madii/domain/joy/application/dto/JoyGetRecommendResponse.java
- src/main/java/com/guttery/madii/domain/joy/application/service/JoyService.java
- src/main/java/com/guttery/madii/domain/joy/domain/repository/JoyQueryDslRepository.java
- src/main/java/com/guttery/madii/domain/joy/infrastructure/JoyRepositoryImpl.java
#166 
- 취향저격 소확행 개별 소확행 북마크 추가 구현
> [Feature] 취향저격 소확행 개별 소확행 북마크 추가 구현

- src/main/java/com/guttery/madii/domain/achievement/presentation/AchievementController.java
- src/main/java/com/guttery/madii/domain/albums/presentation/AlbumController.java
- src/main/java/com/guttery/madii/domain/file/presentation/FileController.java
- src/main/java/com/guttery/madii/domain/joy/presentation/JoyController.java
- src/main/java/com/guttery/madii/domain/notice/presentation/NoticeController.java
- src/main/java/com/guttery/madii/domain/notification/presentation/NotificationController.java
- src/main/java/com/guttery/madii/domain/placeholder/presentation/PlaceholderController.java
- src/main/java/com/guttery/madii/domain/user/presentation/UserController.java
#175 
- API 버전 분리 (uri /v1 추가)
> [Feature] API 버전 분리 (uri /v1 추가)

- build.gradle
- src/main/java/com/guttery/madii/common/exception/ErrorDetails.java
- src/main/java/com/guttery/madii/domain/mail/application/MailSendService.java
- src/main/java/com/guttery/madii/domain/mail/application/MailVerificationCodeGenerator.java
- src/main/java/com/guttery/madii/domain/mail/application/MailVerifyService.java
- src/main/java/com/guttery/madii/domain/mail/presentation/MailController.java
- src/main/resources/templates/mail.html
#173
- 이메일 전송 및 인증 기능 구현
- 템플릿 보완 필요
> [Feature] 이메일 전송 및 인증 기능 구현

- src/main/java/com/guttery/madii/common/config/security/SecurityConstant.java
- src/main/java/com/guttery/madii/domain/mail/application/dto/MailVerificationCodeResponse.java
- src/main/java/com/guttery/madii/domain/mail/application/service/MailSendService.java
- src/main/java/com/guttery/madii/domain/mail/application/service/MailVerificationCodeGenerator.java
- src/main/java/com/guttery/madii/domain/mail/application/service/MailVerifyService.java
- src/main/java/com/guttery/madii/domain/mail/presentation/MailController.java
#173
- 이메일 API 응답 구현 및 헤더 필요 없는 URI에 추가
> [Fix] 이메일 API 보완

- src/main/resources/templates/mail.html
> [Fix] 이메일 템플릿 디자인 수정

- src/main/java/com/guttery/madii/domain/achievement/application/service/JoyPlaylistService.java
- src/main/java/com/guttery/madii/domain/achievement/domain/repository/AchievementQueryDslRepository.java
- src/main/java/com/guttery/madii/domain/achievement/infrastructure/AchievementRepositoryImpl.java
close #186
- 00시부터 01시 사이는 전날로 변환되도록 메소드 구현
> [Fix] 오플리 00시 ~ 01시 조회 문제 수정

- src/main/java/com/guttery/madii/common/config/scheduling/SchedulerConfig.java
close #181
- SchedulerConfig에 @Profile 어노테이션 추가
> [Fix] Prod 환경이 아닌 경우 알림 가지 않도록 수정

- build.gradle
- src/main/java/com/guttery/madii/common/exception/CustomException.java
- src/main/java/com/guttery/madii/common/exception/SentryCapturingHelper.java
close #192
- Sentry 연동
- prod 환경에서만 실행되도록 구현
- p6spy 설정
> [Configuration] Sentry 관련 설정

- src/main/java/com/guttery/madii/domain/achievement/infrastructure/AchievementRepositoryImpl.java
> [Fix] user -> achiever로 수정

- src/main/java/com/guttery/madii/common/config/security/SecurityConstant.java
- src/main/java/com/guttery/madii/domain/user/application/dto/ResetPasswordRequest.java
- src/main/java/com/guttery/madii/domain/user/application/service/LoginInfoService.java
- src/main/java/com/guttery/madii/domain/user/application/service/UserServiceHelper.java
- src/main/java/com/guttery/madii/domain/user/domain/repository/UserRepository.java
- src/main/java/com/guttery/madii/domain/user/presentation/UserController.java
> [Fix] 비밀번호 재설정 API 수정 (#198)

- src/main/java/com/guttery/madii/domain/joy/application/dto/JoyGetDetailResponse.java
- src/main/java/com/guttery/madii/domain/joy/application/service/JoyService.java
- src/main/java/com/guttery/madii/domain/joy/domain/repository/JoyQueryDslRepository.java
- src/main/java/com/guttery/madii/domain/joy/infrastructure/JoyRepositoryImpl.java
- src/main/java/com/guttery/madii/domain/joy/presentation/JoyController.java
close #200 
- 소확행 상세 조회 API 구현
> [Feature] 소확행 상세 조회 API 구현

- src/main/java/com/guttery/madii/common/exception/ErrorDetails.java
- src/main/java/com/guttery/madii/domain/albums/application/service/AlbumService.java
- src/main/java/com/guttery/madii/domain/albums/domain/model/Album.java
- src/main/java/com/guttery/madii/domain/albums/infrastructure/AlbumRepositoryImpl.java
- src/main/java/com/guttery/madii/domain/albums/presentation/AlbumController.java
close #202 
- ALBUM 도메인 official_set_at 컬럼 생성
- 전체 앨범 조회 시 정렬 조건 변경
- 앨범 공개 여부 수정 시 예외 처리 추가
> [Feature] 전체 앨범 조회 시 정렬 조건 변경

- src/main/java/com/guttery/madii/domain/achievement/infrastructure/AchievementRepositoryImpl.java
> [Feature] 오플리 정렬 로직 수정

- src/main/java/com/guttery/madii/domain/albums/infrastructure/AlbumRepositoryImpl.java
close #207 
- joyInfoList 조회 시 joyOrder로 오름차순 정렬 조건 적용
> [Feature] 앨범 상세 조회 API 수정

- src/main/java/com/guttery/madii/domain/albums/application/service/AlbumService.java
- src/main/java/com/guttery/madii/domain/albums/domain/repository/SavingJoyRepository.java
- src/main/java/com/guttery/madii/domain/joy/application/service/JoyService.java
close #210
JPA Repository 메소드 명 수정, service null 처리 방법 수정
> [Fix] 소확행 수정 API 버그

- .github/workflows/ncp-deploy.yml
- Dockerfile
related to #212 
- Github Actions 스크립트 작성 
- Dockerfile 작성
> [Deployment] NCP 마이그레이션을 위한 Github Actions, Dockerfile 작성
